/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tim.pkg7.pbo;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sukma Nur
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSukma = new javax.swing.JButton();
        bNaila = new javax.swing.JButton();
        bFatim = new javax.swing.JButton();
        bAndus = new javax.swing.JButton();
        bAzka = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bNiken = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(532, 532));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(532, 532));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIM 7 || PBO");

        bSukma.setBackground(new java.awt.Color(51, 51, 51));
        bSukma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bSukma.setForeground(new java.awt.Color(255, 255, 255));
        bSukma.setText("Sukma Nur Sholehah");
        bSukma.setFocusPainted(false);
        bSukma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSukma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSukmaActionPerformed(evt);
            }
        });

        bNaila.setBackground(new java.awt.Color(51, 51, 51));
        bNaila.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bNaila.setForeground(new java.awt.Color(255, 255, 255));
        bNaila.setText("Naila Binti Fauziah");
        bNaila.setFocusPainted(false);
        bNaila.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNaila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNailaActionPerformed(evt);
            }
        });

        bFatim.setBackground(new java.awt.Color(51, 51, 51));
        bFatim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bFatim.setForeground(new java.awt.Color(255, 255, 255));
        bFatim.setText("Fatimatuz Zahro'");
        bFatim.setFocusPainted(false);
        bFatim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bFatim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFatimActionPerformed(evt);
            }
        });

        bAndus.setBackground(new java.awt.Color(51, 51, 51));
        bAndus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAndus.setForeground(new java.awt.Color(255, 255, 255));
        bAndus.setText("Muh Riyadlus Sholihiin");
        bAndus.setFocusPainted(false);
        bAndus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAndus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAndusActionPerformed(evt);
            }
        });

        bAzka.setBackground(new java.awt.Color(51, 51, 51));
        bAzka.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAzka.setForeground(new java.awt.Color(255, 255, 255));
        bAzka.setText("Muh Azka Al Fawwaz");
        bAzka.setFocusPainted(false);
        bAzka.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAzka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAzkaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tim/pkg7/pbo/foto/logo-itm-50.png"))); // NOI18N

        bNiken.setBackground(new java.awt.Color(51, 51, 51));
        bNiken.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bNiken.setForeground(new java.awt.Color(255, 255, 255));
        bNiken.setText("Niken Ayu Zaskia Fironica");
        bNiken.setFocusPainted(false);
        bNiken.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNiken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNikenActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bNiken, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSukma, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bNaila, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bFatim, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAndus, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAzka, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSukma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bNiken, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bNaila, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bFatim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bAndus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bAzka, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bNailaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNailaActionPerformed
        // TODO add your handling code here:
         new naila().setVisible(true);
        bNaila.setBackground(new Color(0, 123, 255));  
        bNiken.setBackground(new Color(51, 51, 51));
        bSukma.setBackground(new Color(51, 51, 51));
        bFatim.setBackground(new Color(51, 51, 51));
        bAndus.setBackground(new Color(51,51,51));
        bAzka.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_bNailaActionPerformed

    private void bSukmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSukmaActionPerformed
        // TODO add your handling code here:
        new sukma().setVisible(true);
        bSukma.setBackground(new Color(0, 123, 255));  
        bNiken.setBackground(new Color(51, 51, 51));
        bNaila.setBackground(new Color(51, 51, 51));
        bFatim.setBackground(new Color(51, 51, 51));
        bAndus.setBackground(new Color(51,51,51));
        bAzka.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_bSukmaActionPerformed

    private void bNikenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNikenActionPerformed
        // TODO add your handling code here:
        new niken().setVisible(true);
        bNiken.setBackground(new Color(0, 123, 255));  
        bSukma.setBackground(new Color(51, 51, 51));
        bNaila.setBackground(new Color(51, 51, 51));
        bFatim.setBackground(new Color(51, 51, 51));
        bAndus.setBackground(new Color(51,51,51));
        bAzka.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_bNikenActionPerformed

    private void bFatimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFatimActionPerformed
        // TODO add your handling code here:
        new fatim().setVisible(true);
        bFatim.setBackground(new Color(0, 123, 255));  
        bNiken.setBackground(new Color(51, 51, 51));
        bNaila.setBackground(new Color(51, 51, 51));
        bSukma.setBackground(new Color(51, 51, 51));
        bAndus.setBackground(new Color(51,51,51));
        bAzka.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_bFatimActionPerformed

    private void bAndusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAndusActionPerformed
        // TODO add your handling code here:
        new riyadlus().setVisible(true);
        bAndus.setBackground(new Color(0, 123, 255));  
        bNiken.setBackground(new Color(51, 51, 51));
        bNaila.setBackground(new Color(51, 51, 51));
        bFatim.setBackground(new Color(51, 51, 51));
        bSukma.setBackground(new Color(51,51,51));
        bAzka.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_bAndusActionPerformed

    private void bAzkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAzkaActionPerformed
        // TODO add your handling code here:
        new azka().setVisible(true);
        bAzka.setBackground(new Color(0, 123, 255));  
        bNiken.setBackground(new Color(51, 51, 51));
        bNaila.setBackground(new Color(51, 51, 51));
        bFatim.setBackground(new Color(51, 51, 51));
        bAndus.setBackground(new Color(51,51,51));
        bSukma.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_bAzkaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAndus;
    private javax.swing.JButton bAzka;
    private javax.swing.JButton bFatim;
    private javax.swing.JButton bNaila;
    private javax.swing.JButton bNiken;
    private javax.swing.JButton bSukma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
